### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by samuaaltonen** [EAlas7alo/swaggi#2]
Aiheesi vaikuttaa oikein sopivalta kurssin työksi. Ohjelman runko ja tarvittavat palaset löytyvät ja oletkin jo aloittanut käyttöliittymien teon. 
Tekstikäyttöliittymän käyttöä voisi helpottaa jos koordinaatistot olisivat myös näkyvillä. Kaltaiselleni noviisille joka ei tiedä shakkiruudun koordinaateista, olisi hyvä jos esimerkiksi taulun ylä- ja vasemmalla puolella olisi koordinaatistot abcdefgh ja 87654321, eli:
Tuohon voisi tehdä myös ehkäpä merkkien selitysohjeen, vaikkapa

1. Start game
2. Pieces help
3. Exit

Tuosta 2. valinnasta tulisi vaikkapa tällainen taulukko:

Character | Piece
------------ | -------------
P | Pawn (soldier)
N | Knight
B | Bishop
R | Rook (tower)
Q | Queen
K | King

En ole varma pystyykö tuohon konsolin tulosteessa käyttämään Unicode merkkejä, jolloin siihen voisi laittaa suoraan pelinappuloiden symbolit: http://en.wikipedia.org/wiki/Chess_symbols_in_Unicode

Sain projektin testit ajettua ja ne myös toimivat. 
Nuo mahdolliset ”lisämausteet” tavallisen pelin lisäksi kuulostaa kivalta idealta. Siinä voisi olla vaikka semmoinenkin mauste, että saa tehdä 2 vuoroa peräkkäin. Näitä tuplavuoroja voisi käyttää vaikka max. 3 kertaa pelin aikana tms. Tuo tuplavuoro toisi peliin aivan uuden ulottuvuuden, kun pitäisi olla valppaana ettei vastustaja saisi tuplavuorolla aikaan liian suurta tuhoa.

Kaiken kaikkiaan olet edistynyt projektissa oikein hyvin ja kaikki näyttää olevan kunnossa.

Projekti ladattu 02.04.2015 klo 16:05

**Comment by EAlas7alo** [comment]
Kiitos palautteesta. Unicode-symbolejen käyttöä en tullut edes ajatelleeksi, pitää kokeilla. Koordinaattien toteutus tekstikäyttöliittymään olivatkin seuraavaksi listalla. 

2 siirron lisämauste vaikuttaa eeppiseltä, lisään sen listaan.
